---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Semantic release
          command: npm run semantic-release
workflows:
    build:
      jobs:
        - build:
            context: semantic-release-npm
